//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U413.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityContainer : DbContext
    {
        public EntityContainer(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ban> Bans { get; set; }
        public DbSet<ChatBufferItem> ChatBuffer { get; set; }
        public DbSet<Invite> Invites { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Reply> Replies { get; set; }
        public DbSet<TopicFollow> TopicFollows { get; set; }
        public DbSet<TopicVisit> TopicVisits { get; set; }
        public DbSet<Topic> Topics { get; set; }
        public DbSet<UserActivityLogItem> UserActivityLog { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ViewedPolicy> ViewedPolicies { get; set; }
        public DbSet<Ignore> Ignores { get; set; }
        public DbSet<ChannelStatus> ChannelStatuses { get; set; }
        public DbSet<Alias> Aliases { get; set; }
        public DbSet<Board> Boards { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Variable> Variables { get; set; }
        public DbSet<ShortURL> ShortURLs { get; set; }
    }
}
