//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U413.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ignore
    {
        public long IgnoreID { get; set; }
        public string InitiatingUser { get; set; }
        public string IgnoredUser { get; set; }
    
        public virtual User User { get; set; }
        public virtual User Ignores { get; set; }
    }
}
