//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U413.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Replies = new HashSet<Reply>();
            this.Followers = new HashSet<TopicFollow>();
            this.Visits = new HashSet<TopicVisit>();
        }
    
        public long TopicID { get; set; }
        public short BoardID { get; set; }
        public string Username { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public bool ModsOnly { get; set; }
        public bool Locked { get; set; }
        public bool Stickied { get; set; }
        public System.DateTime LastEdit { get; set; }
        public string EditedBy { get; set; }
        public bool GlobalSticky { get; set; }
    
        public virtual ICollection<Reply> Replies { get; set; }
        public virtual ICollection<TopicFollow> Followers { get; set; }
        public virtual ICollection<TopicVisit> Visits { get; set; }
        public virtual User User { get; set; }
        public virtual Board Board { get; set; }
    }
}
