//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U413.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public Board()
        {
            this.Topics = new HashSet<Topic>();
        }
    
        public short BoardID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Hidden { get; set; }
        public bool ModsOnly { get; set; }
        public bool Locked { get; set; }
        public bool Anonymous { get; set; }
    
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
