//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U413.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public long ReplyID { get; set; }
        public long TopicID { get; set; }
        public string Username { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Body { get; set; }
        public bool ModsOnly { get; set; }
        public System.DateTime LastEdit { get; set; }
        public string EditedBy { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
        public virtual User UserEdited { get; set; }
    }
}
