//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U413.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ChatBuffer = new HashSet<ChatBufferItem>();
            this.InviteCodes = new HashSet<Invite>();
            this.SentMessages = new HashSet<Message>();
            this.ReceivedMessages = new HashSet<Message>();
            this.Replies = new HashSet<Reply>();
            this.FollowedTopics = new HashSet<TopicFollow>();
            this.VisitedTopics = new HashSet<TopicVisit>();
            this.Topics = new HashSet<Topic>();
            this.UserActivityLog = new HashSet<UserActivityLogItem>();
            this.ViewedPolicies = new HashSet<ViewedPolicy>();
            this.RepliesEdited = new HashSet<Reply>();
            this.Ignores = new HashSet<Ignore>();
            this.IgnoredBy = new HashSet<Ignore>();
            this.Channel_Status = new HashSet<ChannelStatus>();
            this.Banned_Users = new HashSet<Ban>();
            this.Roles = new HashSet<Role>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime JoinDate { get; set; }
        public System.DateTime LastLogin { get; set; }
        public string Email { get; set; }
        public bool NotifyReplies { get; set; }
        public bool NotifyMessages { get; set; }
        public bool AutoFollow { get; set; }
        public string Gender { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Location { get; set; }
        public string Bio { get; set; }
        public long Bits { get; set; }
        public string TimeZone { get; set; }
        public bool Sound { get; set; }
        public bool ChatOpen { get; set; }
        public bool ShowTimestamps { get; set; }
    
        public virtual Ban BanInfo { get; set; }
        public virtual ICollection<ChatBufferItem> ChatBuffer { get; set; }
        public virtual ICollection<Invite> InviteCodes { get; set; }
        public virtual ICollection<Message> SentMessages { get; set; }
        public virtual ICollection<Message> ReceivedMessages { get; set; }
        public virtual ICollection<Reply> Replies { get; set; }
        public virtual ICollection<TopicFollow> FollowedTopics { get; set; }
        public virtual ICollection<TopicVisit> VisitedTopics { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
        public virtual ICollection<UserActivityLogItem> UserActivityLog { get; set; }
        public virtual ICollection<ViewedPolicy> ViewedPolicies { get; set; }
        public virtual ICollection<Reply> RepliesEdited { get; set; }
        public virtual ICollection<Ignore> Ignores { get; set; }
        public virtual ICollection<Ignore> IgnoredBy { get; set; }
        public virtual ICollection<ChannelStatus> Channel_Status { get; set; }
        public virtual ICollection<Ban> Banned_Users { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
