//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U413.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatBufferItem
    {
        public long ID { get; set; }
        public string Channel { get; set; }
        public string Username { get; set; }
        public System.DateTime SentDate { get; set; }
        public string Text { get; set; }
    
        public virtual User User { get; set; }
    }
}
